version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - straightchlorine
    labels:
      - dependencies
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - straightchlorine
    labels:
      - ci
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - straightchlorine
    labels:
      - docker
    open-pull-requests-limit: 5
